name: wiki

on:
  push:
    branches: [ "main", "44-wiki-pages-workflow" ]
    paths: [ "res/articles/*" ]

jobs:
  sync-to-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Sync docs to wiki
        uses: newrelic/wiki-sync-action@main
        with:
          branch: main
          source: docs
          destination: wiki
          token: ${{ secrets.TOKEN }}
    
